export type AdminLocale = "en" | "km";

const km: Record<string, string> = {
  "Dashboard": "ផ្ទាំងគ្រប់គ្រង", "Categories": "ប្រភេទ", "Currencies": "រូបិយបណ្ណ", "AI Support": "ជំនួយ AI", "Users": "អ្នកប្រើប្រាស់", "Reviews": "មតិកែលម្អ", "Alert Rules": "ច្បាប់ជូនដំណឹង", "Notifications": "ការជូនដំណឹង", "Reports": "របាយការណ៍", "Settings": "ការកំណត់",
  "Good morning": "អរុណសួស្តី", "Good afternoon": "ទិវាសួស្តី", "Good evening": "សាយណ្ហសួស្តី", "Here’s what’s happening across iStash today.": "នេះជាស្ថានភាពទូទៅរបស់ iStash នៅថ្ងៃនេះ។", "Registered accounts": "គណនីដែលបានចុះឈ្មោះ", "Configured rules": "ច្បាប់ដែលបានកំណត់", "System notifications": "ការជូនដំណឹងប្រព័ន្ធ",
  "User Overview": "ទិដ្ឋភាពអ្នកប្រើប្រាស់", "Understand the current iStash user distribution.": "ស្វែងយល់ពីការបែងចែកអ្នកប្រើប្រាស់ iStash បច្ចុប្បន្ន។", "Gender": "ភេទ", "Age": "អាយុ", "Male": "ប្រុស", "Female": "ស្រី", "Other": "ផ្សេងៗ", "Prefer Not To Say": "មិនចង់បញ្ជាក់", "Unspecified": "មិនបានបញ្ជាក់", "Under 15": "ក្រោម ១៥", "Unknown": "មិនស្គាល់",
  "System Health": "សុខភាពប្រព័ន្ធ", "Currency provider availability and synchronization.": "ស្ថានភាព និងការធ្វើសមកាលកម្មរបស់អ្នកផ្តល់រូបិយបណ្ណ។", "Provider Issue": "បញ្ហាអ្នកផ្តល់សេវា", "Last Successful Sync": "សមកាលកម្មជោគជ័យចុងក្រោយ", "Currencies Received": "រូបិយបណ្ណដែលទទួលបាន", "Rates Updated": "អត្រាដែលបានកែប្រែ", "Data Status": "ស្ថានភាពទិន្នន័យ", "Up to date": "ទាន់សម័យ", "View Currencies": "មើលរូបិយបណ្ណ",
  "Needs Attention": "ត្រូវការការយកចិត្តទុកដាក់", "Items that may require administrator attention.": "ធាតុដែលអាចត្រូវការការយកចិត្តទុកដាក់ពីអ្នកគ្រប់គ្រង។", "Pending Reviews": "មតិកំពុងរង់ចាំ", "Critical Alert Rules": "ច្បាប់ជូនដំណឹងធ្ងន់ធ្ងរ", "Need attention": "ត្រូវការការយកចិត្តទុកដាក់", "System health": "សុខភាពប្រព័ន្ធ",
  "Recent Reviews": "មតិថ្មីៗ", "Latest feedback submitted by users.": "មតិចុងក្រោយដែលបានផ្ញើដោយអ្នកប្រើប្រាស់។", "Recent Notifications": "ការជូនដំណឹងថ្មីៗ", "Latest system messages sent to users.": "សារប្រព័ន្ធចុងក្រោយដែលបានផ្ញើទៅអ្នកប្រើប្រាស់។", "View All Reviews": "មើលមតិទាំងអស់", "View All Notifications": "មើលការជូនដំណឹងទាំងអស់", "Read": "បានអាន", "Unread": "មិនទាន់អាន",
  "Quick Management": "ការគ្រប់គ្រងរហ័ស", "Open frequently used administration areas.": "បើកផ្នែកគ្រប់គ្រងដែលប្រើញឹកញាប់។", "Manage user accounts": "គ្រប់គ្រងគណនីអ្នកប្រើប្រាស់", "Organize financial categories": "រៀបចំប្រភេទហិរញ្ញវត្ថុ", "Monitor currencies and rates": "តាមដានរូបិយបណ្ណ និងអត្រា", "Monitor and send notifications": "តាមដាន និងផ្ញើការជូនដំណឹង", "Review user feedback": "ពិនិត្យមតិអ្នកប្រើប្រាស់", "Inspect notification rules": "ពិនិត្យច្បាប់ជូនដំណឹង",
  "Search...": "ស្វែងរក...", "Administrator": "អ្នកគ្រប់គ្រងប្រព័ន្ធ", "Sign out": "ចាកចេញ", "Switch language": "ប្តូរភាសា", "English": "អង់គ្លេស", "Khmer": "ខ្មែរ",
  "User Management": "ការគ្រប់គ្រងអ្នកប្រើប្រាស់", "Manage, monitor, and control iStash user accounts.": "គ្រប់គ្រង តាមដាន និងត្រួតពិនិត្យគណនីអ្នកប្រើប្រាស់ iStash។", "Add User": "បន្ថែមអ្នកប្រើប្រាស់",
  "Currency Management": "ការគ្រប់គ្រងរូបិយបណ្ណ", "Manage supported currencies, exchange-rate synchronization, and provider availability.": "គ្រប់គ្រងរូបិយបណ្ណ អត្រាប្តូរប្រាក់ និងស្ថានភាពអ្នកផ្តល់សេវា។", "Synchronize": "ធ្វើសមកាលកម្ម", "Synchronizing...": "កំពុងធ្វើសមកាលកម្ម...",
  "Category Management": "ការគ្រប់គ្រងប្រភេទ", "Manage income, expense, system, default, and hierarchical categories used throughout iStash.": "គ្រប់គ្រងប្រភេទចំណូល ចំណាយ ប្រព័ន្ធ លំនាំដើម និងឋានានុក្រមក្នុង iStash។", "Add Category": "បន្ថែមប្រភេទ",
  "Reviews & Feedback": "មតិ និងការវាយតម្លៃ", "Review and manage user suggestions, bug reports, complaints, compliments, and general feedback.": "ពិនិត្យ និងគ្រប់គ្រងសំណើ របាយការណ៍បញ្ហា បណ្តឹង ការសរសើរ និងមតិទូទៅ។",
  "Monitor user alert rules, trigger conditions, severity, references, and execution schedules.": "តាមដានច្បាប់ជូនដំណឹង លក្ខខណ្ឌកេះ កម្រិតធ្ងន់ធ្ងរ ឯកសារយោង និងកាលវិភាគ។",
  "Monitor notification activity, delivery, and system messages.": "តាមដានសកម្មភាពជូនដំណឹង ការបញ្ជូន និងសារប្រព័ន្ធ។", "Send Notification": "ផ្ញើការជូនដំណឹង",
  "Total Users": "អ្នកប្រើប្រាស់សរុប", "Active Users": "អ្នកប្រើសកម្ម", "Suspended Users": "អ្នកប្រើដែលផ្អាក", "Onboarding Completed": "បានបញ្ចប់ការណែនាំ",
  "User Distribution": "ការបែងចែកអ្នកប្រើប្រាស់", "All alert rules": "ច្បាប់ជូនដំណឹងទាំងអស់", "Currently active": "កំពុងដំណើរការ", "High-priority rules": "ច្បាប់អាទិភាពខ្ពស់", "Warning-level rules": "ច្បាប់កម្រិតប្រុងប្រយ័ត្ន",
  "Total Currencies": "រូបិយបណ្ណសរុប", "Active Currencies": "រូបិយបណ្ណសកម្ម", "Inactive Currencies": "រូបិយបណ្ណអសកម្ម", "Provider Health": "សុខភាពអ្នកផ្តល់សេវា", "Supported Currencies": "រូបិយបណ្ណដែលគាំទ្រ", "Currency Provider": "អ្នកផ្តល់រូបិយបណ្ណ",
  "Total Categories": "ប្រភេទសរុប", "Income": "ចំណូល", "Expense": "ចំណាយ", "System Categories": "ប្រភេទប្រព័ន្ធ",
  "Total Reviews": "មតិសរុប", "Pending": "កំពុងរង់ចាំ", "In Review": "កំពុងពិនិត្យ", "Resolved": "បានដោះស្រាយ", "Closed": "បានបិទ",
  "User submissions": "មតិពីអ្នកប្រើប្រាស់", "Awaiting review": "កំពុងរង់ចាំពិនិត្យ", "Currently handled": "កំពុងដោះស្រាយ", "Completed reviews": "មតិដែលបានដោះស្រាយ",
  "Total Rules": "ច្បាប់សរុប", "Enabled": "បានបើក", "Disabled": "បានបិទ", "Critical": "ធ្ងន់ធ្ងរ", "Warning": "ប្រុងប្រយ័ត្ន", "Info": "ព័ត៌មាន",
  "Search by currency code or name...": "ស្វែងរកតាមកូដ ឬឈ្មោះរូបិយបណ្ណ...", "Search by category name or keyword...": "ស្វែងរកតាមឈ្មោះ ឬពាក្យគន្លឹះ...", "Search by name, username, or email...": "ស្វែងរកតាមឈ្មោះ ឈ្មោះអ្នកប្រើ ឬអ៊ីមែល...",
  "All Types": "ប្រភេទទាំងអស់", "All Statuses": "ស្ថានភាពទាំងអស់", "All Categories": "ប្រភេទទាំងអស់", "All Levels": "កម្រិតទាំងអស់", "All Users": "អ្នកប្រើទាំងអស់", "All Alert Types": "ប្រភេទជូនដំណឹងទាំងអស់", "All Triggers": "លក្ខខណ្ឌកេះទាំងអស់", "All Severities": "កម្រិតទាំងអស់", "All References": "ឯកសារយោងទាំងអស់",
  "Reset": "កំណត់ឡើងវិញ", "Reset Filters": "កំណត់តម្រងឡើងវិញ", "Retry": "ព្យាយាមម្តងទៀត", "Previous": "មុន", "Next": "បន្ទាប់", "Actions": "សកម្មភាព", "Status": "ស្ថានភាព", "Created": "បានបង្កើត", "Updated": "បានកែប្រែ", "Type": "ប្រភេទ", "User": "អ្នកប្រើប្រាស់", "Rule": "ច្បាប់", "Trigger": "លក្ខខណ្ឌកេះ", "Severity": "កម្រិត", "Next Trigger": "កេះបន្ទាប់", "Reference": "ឯកសារយោង", "Rating": "ការវាយតម្លៃ", "Review": "មតិ", "Parent": "ប្រភេទមេ", "Classification": "ចំណាត់ថ្នាក់", "Category": "ប្រភេទ", "Currency": "រូបិយបណ្ណ", "Provider": "អ្នកផ្តល់សេវា", "Last Synced": "សមកាលកម្មចុងក្រោយ", "Decimal Places": "ខ្ទង់ទសភាគ", "Symbol": "និមិត្តសញ្ញា",
  "Daily Expense Reminder": "រំលឹកចំណាយប្រចាំថ្ងៃ", "Budget Threshold": "កម្រិតថវិកា", "Savings Reminder": "រំលឹកការសន្សំ", "Recurring Reminder": "រំលឹកប្រតិបត្តិការប្រចាំ", "Monthly Summary": "សេចក្តីសង្ខេបប្រចាំខែ", "Time": "ពេលវេលា", "Threshold": "កម្រិត", "Event": "ព្រឹត្តិការណ៍", "Schedule": "កាលវិភាគ", "Budget": "ថវិកា", "Savings Goal": "គោលដៅសន្សំ", "Recurring Transaction": "ប្រតិបត្តិការប្រចាំ",
  "Available currencies": "រូបិយបណ្ណដែលមាន", "Enabled in iStash": "បានបើកក្នុង iStash", "Currently disabled": "បានបិទបច្ចុប្បន្ន", "Loading": "កំពុងផ្ទុក", "Healthy": "ដំណើរការល្អ", "Issue": "មានបញ្ហា", "Data may be outdated": "ទិន្នន័យអាចហួសសម័យ", "Provider availability": "ស្ថានភាពអ្នកផ្តល់សេវា", "All categories": "ប្រភេទទាំងអស់", "Income categories": "ប្រភេទចំណូល", "Expense categories": "ប្រភេទចំណាយ", "Managed by iStash": "គ្រប់គ្រងដោយ iStash",
  "View Details": "មើលព័ត៌មានលម្អិត", "Details": "ព័ត៌មានលម្អិត", "Save Changes": "រក្សាទុកការផ្លាស់ប្តូរ", "Cancel": "បោះបង់", "Delete Review": "លុបមតិ", "Edit Category": "កែសម្រួលប្រភេទ", "Delete Category": "លុបប្រភេទ", "Activate": "បើកដំណើរការ", "Deactivate": "បិទដំណើរការ",
  "Create Category": "បង្កើតប្រភេទ", "Create User": "បង្កើតអ្នកប្រើប្រាស់", "Update Status": "កែប្រែស្ថានភាព", "Move to Root": "ផ្លាស់ទីទៅកម្រិតដើម",
  "No reviews yet": "មិនទាន់មានមតិទេ", "No alert rules found": "រកមិនឃើញច្បាប់ជូនដំណឹង", "No currencies available": "មិនមានរូបិយបណ្ណ", "No categories yet": "មិនទាន់មានប្រភេទទេ", "Please try again.": "សូមព្យាយាមម្តងទៀត។",
  "Account Settings": "ការកំណត់គណនី", "My Profile": "ព័ត៌មានគណនីរបស់ខ្ញុំ", "Manage your personal information, profile photo, and account security.": "គ្រប់គ្រងព័ត៌មានផ្ទាល់ខ្លួន រូបថតគណនី និងសុវត្ថិភាពគណនី។", "Overview": "ទិដ្ឋភាពទូទៅ", "Edit Profile": "កែប្រែព័ត៌មាន", "Security": "សុវត្ថិភាព", "Profile sections": "ផ្នែកព័ត៌មានគណនី", "Change profile photo": "ប្តូររូបថតគណនី", "Active": "សកម្ម", "Inactive": "អសកម្ម", "Location not provided": "មិនបានបញ្ជាក់ទីតាំង", "Joined": "បានចូលរួម", "Join date unavailable": "មិនមានថ្ងៃចូលរួម", "Email verified": "អ៊ីមែលបានផ្ទៀងផ្ទាត់", "Personal Information": "ព័ត៌មានផ្ទាល់ខ្លួន", "Account identity and contact information.": "អត្តសញ្ញាណគណនី និងព័ត៌មានទំនាក់ទំនង។", "First Name": "នាមត្រកូល", "Last Name": "នាមខ្លួន", "Email Address": "អាសយដ្ឋានអ៊ីមែល", "Phone Number": "លេខទូរស័ព្ទ", "Location": "ទីតាំង", "Occupation": "មុខរបរ", "Account Status": "ស្ថានភាពគណនី", "Account": "គណនី", "Email Verified": "អ៊ីមែលបានផ្ទៀងផ្ទាត់", "Profile Completed": "ព័ត៌មានបានបំពេញ", "Preferences": "ចំណូលចិត្ត", "Language": "ភាសា", "Timezone": "តំបន់ពេលវេលា", "Last Updated": "បានកែប្រែចុងក្រោយ", "Unable to load profile": "មិនអាចទាញយកព័ត៌មានគណនីបានទេ", "We could not load your account information. Please try again.": "មិនអាចទាញយកព័ត៌មានគណនីបានទេ។ សូមព្យាយាមម្តងទៀត។",
  "Change Password": "ផ្លាស់ប្តូរពាក្យសម្ងាត់", "Choose a strong password that you do not use for another account.": "ជ្រើសរើសពាក្យសម្ងាត់រឹងមាំដែលអ្នកមិនប្រើសម្រាប់គណនីផ្សេង។", "New Password": "ពាក្យសម្ងាត់ថ្មី", "Enter your new password": "បញ្ចូលពាក្យសម្ងាត់ថ្មី", "Confirm New Password": "បញ្ជាក់ពាក្យសម្ងាត់ថ្មី", "Enter the new password again": "បញ្ចូលពាក្យសម្ងាត់ថ្មីម្តងទៀត", "Password strength": "កម្រិតសុវត្ថិភាពពាក្យសម្ងាត់", "Weak": "ខ្សោយ", "Fair": "មធ្យម", "Good": "ល្អ", "Strong": "រឹងមាំ", "Updating...": "កំពុងកែប្រែ...", "Password Requirements": "លក្ខខណ្ឌពាក្យសម្ងាត់", "Use these guidelines to keep your administrator account secure.": "អនុវត្តតាមគោលការណ៍ទាំងនេះ ដើម្បីរក្សាសុវត្ថិភាពគណនីអ្នកគ្រប់គ្រង។", "At least 8 characters": "យ៉ាងហោចណាស់ ៨ តួអក្សរ", "At least one uppercase letter": "មានអក្សរធំយ៉ាងហោចណាស់ ១", "At least one number": "មានលេខយ៉ាងហោចណាស់ ១", "At least one special character": "មានតួអក្សរពិសេសយ៉ាងហោចណាស់ ១", "After changing your password, use the new password the next time you sign in.": "បន្ទាប់ពីប្តូរពាក្យសម្ងាត់ សូមប្រើពាក្យសម្ងាត់ថ្មីនៅពេលចូលប្រើលើកក្រោយ។", "Password changed successfully.": "បានផ្លាស់ប្តូរពាក្យសម្ងាត់ដោយជោគជ័យ។", "Unable to change password. Please try again.": "មិនអាចផ្លាស់ប្តូរពាក្យសម្ងាត់បានទេ។ សូមព្យាយាមម្តងទៀត។",
};

export function translateAdmin(locale: AdminLocale, text: string) {
  return locale === "km" ? km[text] ?? text : text;
}
