export {};
const API_URL = "https://ite-api.istashkh.com/api/v1";
const TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJfRFo0Y3dBMG50cmtUODE5SlRxaUhFcEo1NFRVcmpmaFFrVWItZk8tWHZRIn0.eyJleHAiOjE3ODY0MDQ3OTQsImlhdCI6MTc4NjM2ODc5OCwiYXV0aF90aW1lIjoxNzg2MzY4Nzk0LCJqdGkiOiJvbnJ0YWM6MWZhMjk4OGItNjlmNC00NDYwLTExZTMtYTgyZjIwZWVlZTQ2IiwiaXNzIjoiaHR0cHM6Ly9pdGUta2V5Y2xvYWsuaXN0YXNoa2guY29tL3JlYWxtcy9pc3Rhc2giLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiYjJmNTA1NmQtOGU2Ny00ZmJmLWEwYmYtN2JiNzhhZTVlMTUzIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaXN0YXNoLWNsaWVudCIsInNpZCI6Ino3ODZnVHZhN2VEWDJOUVI5VXQtb2o4TiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaHR0cHM6Ly9pLXN0YXNoLWZyb250LWVuZC52ZXJjZWwuYXBwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWlzdGFzaCIsIm9mZmxpbmVfYWNjZXNzIiwiQURNSU4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsIlVTRVIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY2Vzcy1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IlJvbmEgTHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbjIiLCJnaXZlbl9uYW1lIjoiUm9uYSIsImZhbWlseV9uYW1lIjoiTHkiLCJlbWFpbCI6InZlbHNvdGhvdW5AZ21haWwuY29tIn0.vnnsre7SKRtfrPNYDZpIzJLSnr5bSfbLG689nA_HZtb4K8kE6qx1rfVI5r5jb4VzTD5xTFYxtQSg21cv9yM3oWsKTeEqOY1mIU4uzJlXma0Y4ouY3_Wgh9gpmf7c5sIZseqBk5bgJ1O_aQziKwYJNpN6Oi-r2vIDqxsFBUlVNakxY21Ddc4uZBqLJyd5ltf6N0tyyiRvMndz5DEKwmVLfnod5ajhDaqZU8_bJw9KyQ-SnWRWaDMZU7PUP7tlnHCSDVZMKonLPHbJGrJ3zaHn6eXEdGN0I5iWUZvipn5nGwFdHUoXMVwkB4l791pHM4r_0v2AEFq7nrOKLNghItLOMQ";

async function testQueryParams() {
  console.log("🔍 Testing query params token...");
  const res1 = await fetch(`${API_URL}/admin/currencies/provider-status?access_token=${TOKEN}`);
  console.log("access_token Status:", res1.status);

  const res2 = await fetch(`${API_URL}/admin/currencies/provider-status?token=${TOKEN}`);
  console.log("token Status:", res2.status);
}

testQueryParams();
